#------------------------------------------------------------
# Values for this lesson.
#------------------------------------------------------------

# Which carpentry is this (swc, dc, lc, or cp)?
# swc: Software Carpentry
# dc: Data Carpentry
# lc: Library Carpentry
# cp: Carpentries (to use for instructor training for instance)
# incubator: The Carpentries Incubator
carpentry: 'incubator'

# Overall title for pages.
title: 'Reproducible HPC workflows using JUBE'

# Date the lesson was created (YYYY-MM-DD, this is empty by default)
created: ~ # FIXME

# Comma-separated list of keywords for the lesson
keywords: 'hpc, workflow, software, lesson, The Carpentries'

# Life cycle stage of the lesson
# possible values: pre-alpha, alpha, beta, stable
life_cycle: 'pre-alpha' # FIXME

# License of the lesson
license: 'CC-BY 4.0'

# Link to the source repository for this lesson
source: 'https://github.com/carpentries/workbench-template-md' # FIXME

# Default branch of your lesson
branch: 'main'

# Who to contact if there are any issues
contact: 'tutorials@hpc.nrw'

# Navigation ------------------------------------------------
#
# Use the following menu items to specify the order of
# individual pages in each dropdown section. Leave blank to
# include all pages in the folder.
#
# Example -------------
#
# episodes:
# - introduction.md
# - first-steps.md
#
# learners:
# - setup.md
#
# instructors:
# - instructor-notes.md
#
# profiles:
# - one-learner.md
# - another-learner.md

# Order of episodes in your lesson
episodes:
  - introduction.md
  - benchmark_example.md
  - jube_workflow.md
  - basic_tags.md
  - initial_step.md
  - build_step.md
  - run_step.md
  - gathering_output.md
  - result_tables.md
  - stage_iterations.md
  - outlook.md

# Information for Learners
learners: 

# Information for Instructors
instructors: 

# Learner Profiles
profiles: 

# Customisation ---------------------------------------------
#
# This space below is where custom yaml items (e.g. pinning
# sandpaper and varnish versions) should live


